<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<CompressionEnabled>false</CompressionEnabled>
		<OverrideHtmlAssetPlaceholders>true</OverrideHtmlAssetPlaceholders>
		<ServiceWorkerAssetsManifest>service-worker-assets.js</ServiceWorkerAssetsManifest>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.2" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.2" PrivateAssets="all" />
		<ProjectReference Include="..\..\..\SpawnDev.BlazorJS.TransformersJS\SpawnDev.BlazorJS.TransformersJS\SpawnDev.BlazorJS.TransformersJS\SpawnDev.BlazorJS.TransformersJS.csproj" />
		<!-- Provides access to various browser APIs and JavaScript interop functionalities, used for integrating with browser features and third-party JavaScript libraries in Rendusa -->
		<!-- <PackageReference Include="SpawnDev.BlazorJS" Version="3.0.1" /> -->
		<!-- Provides the backend for the WebTorrent Virtual File System Provider -->
		<ProjectReference Include="..\..\..\SpawnDev.BlazorJS.WebTorrents\SpawnDev.BlazorJS.WebTorrents\SpawnDev.BlazorJS.WebTorrents\SpawnDev.BlazorJS.WebTorrents.csproj" />
		<ProjectReference Include="..\..\..\SpawnDev.BlazorJS\SpawnDev.BlazorJS\SpawnDev.BlazorJS\SpawnDev.BlazorJS.csproj" />
		
		<!-- Provides access to Transformers.js and AI models, primarily used for monocular depth estimation with DepthAnythingV2 for autoamtic 2D to 3D covnersion -->
		<!-- <PackageReference Include="SpawnDev.BlazorJS.TransformersJS" Version="2.0.0" /> -->
		<!-- Provides access to the Web Crypto API for cryptographic operations, used for secure key management, encryption/decryption, and other cryptographic functionalities in Rendusa -->
		<PackageReference Include="SpawnDev.BlazorJS.Cryptography" Version="3.0.0" />
		<!-- Provides access to PeerJS for WebRTC-based peer-to-peer communication, used for media streaming/sharing via WebRTC VFS backend and other real-time features in Rendusa -->
		<PackageReference Include="SpawnDev.BlazorJS.PeerJS" Version="2.0.0" />
		<!-- Provides access to ILGPU for GPU-accelerated computations in the browser using WebGPU and WebGL, used for performance-critical tasks such as real-time video processing, physics simulations, and other computationally intensive operations in Rendusa -->
		<PackageReference Include="SpawnDev.ILGPU" Version="2.3.0" />
		<!-- Allows accessing Rendusa's Virtual File System from a folder on Windows -->
		<PackageReference Include="SpawnDev.WebFS" Version="2.0.0" />
	</ItemGroup>

	<ItemGroup>
		<ServiceWorker Include="wwwroot\service-worker.js" PublishedContent="wwwroot\service-worker.published.js" />
	</ItemGroup>

</Project>
